#####################################################################
# +---------------------------------------------------------------+ #
# |                       Basic Settings                          | #
# +---------------------------------------------------------------+ #
#####################################################################

language: "en" # Supported languages -> hu, de, en, tr, es
starting-balance: 500

database:
  type: "sqlite" # Supported database types -> sqlite, mysql
  mysql:
    host: "localhost"
    port: 3306
    database: "coma112"
    username: "root"
    password: ""
    # You shouldn't touch this part except if you are familiar with it.
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000

##########################################################################
# +--------------------------------------------------------------------+ #
# |                       Formatting settings                          | #
# +------------------------------------------------------------------- + #
##########################################################################

formatting:
  enabled: true
  type: dot
  basic:
    '1000': K
    '1000000': M
    '1000000000': B
    '1000000000000': T

# Types

# dot = 1.000.000
# commas = 1,000,000
# basic = 1M

###############################################################
# +---------------------------------------------------------+ #
# |                       FEATURES                          | #
# +-------------------------------------------------------- + #
###############################################################

features:
  badges:
    enabled: true
    multiplier: 0.5 # Token * Mutliplier = XP | Example: 50 Token = 25 XP

    # Displaynames
    novice: "Novice"
    beginner: "Beginner"
    competence: "Competence"
    proficient: "Proficient"
    expert: "Expert"

    # XP Limits
    limit:
      novice: 1000
      beginner: 2000
      competence: 3000
      proficient: 4000
      expert: 5000

###############################################################
# +---------------------------------------------------------+ #
# |                       WEBHOOKS                          | #
# +-------------------------------------------------------- + #
###############################################################

webhook:
  balance-add-embed:
    enabled: false
    url: "WEBHOOK URL HERE"
    title: "BALANCE ADD"
    description: "**{player}** Added: **{addedAmount}** Old Balance: **{oldBalance}**"
    color: "YELLOW"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CTOKEN"
    footer-icon: ""
    thumbnail: ""
    image: ""
  balance-reset-embed:
    enabled: false
    url: "WEBHOOK URL HERE"
    title: "BALANCE RESET"
    description: "**{player}**'s balance has been reset. Old Balance: **{oldBalance}**"
    color: "YELLOW"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CTOKEN"
    footer-icon: ""
    thumbnail: ""
    image: ""
  balance-set-embed:
    enabled: false
    url: "WEBHOOK URL HERE"
    title: "BALANCE SET"
    description: "**{player}** New Balance: **{newBalance}** Old Balance: **{oldBalance}**"
    color: "YELLOW"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CTOKEN"
    footer-icon: ""
    thumbnail: ""
    image: ""
  balance-take-embed:
    enabled: false
    url: "WEBHOOK URL HERE"
    title: "BALANCE TAKE"
    description: "**{player}** New Balance: **{takenAmount}** Old Balance: **{oldBalance}**"
    color: "YELLOW"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CTOKEN"
    footer-icon: ""
    thumbnail: ""
    image: ""
  balance-reset-all-embed:
    enabled: false
    url: "WEBHOOK URL HERE"
    title: "BALANCE RESET"
    description: "Everyone's balance has been reset!"
    color: "YELLOW"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CTOKEN"
    footer-icon: ""
    thumbnail: ""
    image: ""
  balance-add-all-embed:
    enabled: false
    url: "WEBHOOK URL HERE"
    title: "BALANCE ADD"
    description: "**{addedAmount}** has been added to everyone's balance"
    color: "YELLOW"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CTOKEN"
    footer-icon: ""
    thumbnail: ""
    image: ""

##################################################################
# +------------------------------------------------------------+ #
# |                       ITEM PRICES                          | #
# +----------------------------------------------------------- + #
##################################################################

prices:
  DIRT: 50
  DIAMOND_BLOCK: 1000